### ISSUE TITLE
dns320-fan.py

### ISSUE THREAD

**Issue by xapukserge** [martignlo/DNS-320L#1]
Hi. You can think I'm dummy, but this script was written for python2. OpenWRT does not use python2, only python3. Could you help me to make changes in this script? 
Here are errors:
root@OpenWrt:~# /usr/bin/fan-daemon.py
Traceback (most recent call last):
File "/usr/bin/fan-daemon.py", line 156, in main
SetPowerLed(port, 1)
File "/usr/bin/fan-daemon.py", line 96, in SetPowerLed
WritePktToSerial(port, POWER_LED_CMD[status])
File "/usr/bin/fan-daemon.py", line 80, in WritePktToSerial
port.write(data)
File "/usr/lib/python3.10/site-packages/serial/serialposix.py", line 532, in write
File "/usr/lib/python3.10/site-packages/serial/serialutil.py", line 63, in to_bytes
TypeError: unicode strings are not supported, please encode to bytes: 'ъ\x03\x06\x01\x00\x01ы'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/bin/fan-daemon.py", line 164, in <module>
main()
File "/usr/bin/fan-daemon.py", line 159, in main
SetFanSpeed(port, 0)
File "/usr/bin/fan-daemon.py", line 114, in SetFanSpeed
WritePktToSerial(port, FAN_SPEED_CMDS[speed])
File "/usr/bin/fan-daemon.py", line 80, in WritePktToSerial
port.write(data)
File "/usr/lib/python3.10/site-packages/serial/serialposix.py", line 532, in write
File "/usr/lib/python3.10/site-packages/serial/serialposix.py", line 532, in write
File "/usr/lib/python3.10/site-packages/serial/serialutil.py", line 63, in to_bytes
TypeError: unicode strings are not supported, please encode to bytes: 'ъ\x02\x00\x00\x00\x00ы'

**Comment by Neustradamus** [comment]
@martignlo, @xapukserge: For information:

Note that D-Link DNS-320L and DNS-325 are supported in OpenWrt:
- https://github.com/openwrt/openwrt/pull/17924
- https://github.com/openwrt/openwrt/pull/16803
- https://github.com/openwrt/openwrt/pull/15433
